title: My GitHub Pages Site
description: This is my awesome GitHub Pages site.
theme: jekyll-theme-primer
baseurl: "https://samwigglesw0rth.github.io/samwigglesw0rthZtM/"

remote_theme: mmistakes/minimal-mistakes
