# Site settings
title: My GitHub Pages Site
description: This is my awesome GitHub Pages site.
theme: jekyll-theme-primer
baseurl: "https://samwigglesw0rth.github.io/samwigglesw0rthZtM/" 

# GitHub Pages settings
 remote_theme:  # If you're using a remote theme

# Other settings...
